In [4]:
n=[[12,7,3],
   [4,5,6],
   [7,8,9]]
n1=[[5,8,1],
   [6,7,3],
   [4,5,9]]
result=[[0,0,0],
       [0,0,0],
       [0,0,0]]
for i in range(len(n)):
    for j in range(len([0])):
        result[i][j]=n[i][j]+n1[i][j]
for r in result:
    print(r)

[17, 0, 0]
[10, 0, 0]
[11, 0, 0]


In [1]:
import numpy as np
n=[[12,7,3],
   [4,5,6],
   [7,8,9]]
n1=[[5,8,1],
   [6,7,3],
   [4,5,9]]
result=[[0,0,0],
       [0,0,0],
       [0,0,0]]
result=np.dot(n,n1)
for r in result:
    print(r)

[114 160  60]
[74 97 73]
[119 157 112]


In [3]:
import numpy
matrix=[[1,2,3],[4,5,6]]
print(matrix)
print("\n")
print(numpy.transpose(matrix))

[[1, 2, 3], [4, 5, 6]]


[[1 4]
 [2 5]
 [3 6]]


In [3]:
str=input()
word=[word.lower() for word in str.split()]
word.sort()
print("The sorted words are:")
for word in word:
    print(word)

a b c g h j y u f 
The sorted words are:
a
b
c
f
g
h
j
u
y


In [5]:
my_string='hello'
print(my_string)

hello
